from __future__ import annotations

import json
import os

import jsonschema

from .shared import (
    fetch_intermediate_representation,
    local_ir_path,
    out_dir,
    to_enum_member_name,
)
from .types import WebScrapingApiIR


def _render_generated_module(api: WebScrapingApiIR) -> str:
    lines: list[str] = []

    lines.append("# Auto-generated by src/decodo/codegen/web_scraping_api/generate_parameter_schemas.py — do not edit")
    lines.append("# JSON Schema objects for each target — used for validation via jsonschema")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("")
    lines.append("request_json_schemas: dict[str, dict] = {")

    for target_key, target in api["targets"].items():
        schema_literal = json.dumps(target["parameter_schema"], indent=2)
        indented = "\n".join(
            line if idx == 0 else f"    {line}"
            for idx, line in enumerate(schema_literal.split("\n"))
        )
        lines.append(f"    {json.dumps(target_key)}: {indented},")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def generate_parameter_schemas_file() -> None:
    ir = fetch_intermediate_representation()
    api = ir["apis"]["webScrapingApi"]

    for target_key, target in api["targets"].items():
        try:
            jsonschema.Draft4Validator.check_schema(target["parameter_schema"])
        except Exception as err:
            raise RuntimeError(
                f'Invalid parameter_schema for target "{target_key}": {err}'
            ) from err

    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "request_schemas.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(_render_generated_module(api))

    target_count = len(api["targets"])
    print(f"Generated request schemas from {local_ir_path}:")
    print(f"  {out_path} ({target_count} targets)")
