from __future__ import annotations

import json
import os
from typing import Any

from .shared import (
    fetch_intermediate_representation,
    local_ir_path,
    out_dir,
)
from .types import WebScrapingApiIR


class _ParameterMeta:
    def __init__(
        self,
        type: str,
        max_length: int | None = None,
        minimum: float | None = None,
        maximum: float | None = None,
        enum: list[Any] | None = None,
        items: dict[str, Any] | None = None,
    ) -> None:
        self.type = type
        self.max_length = max_length
        self.minimum = minimum
        self.maximum = maximum
        self.enum = enum
        self.items = items


def _to_parameter_meta(schema: dict[str, Any]) -> _ParameterMeta:
    meta = _ParameterMeta(type=str(schema.get("type", "string")))
    if schema.get("maxLength") is not None:
        meta.max_length = schema["maxLength"]
    if schema.get("minimum") is not None:
        meta.minimum = schema["minimum"]
    if schema.get("maximum") is not None:
        meta.maximum = schema["maximum"]
    if isinstance(schema.get("enum"), list):
        meta.enum = schema["enum"]
    if schema.get("type") == "array" and schema.get("items"):
        items = schema["items"]
        if isinstance(items, list):
            items = items[0] if items else {}
        if isinstance(items, dict) and "type" in items:
            meta.items = {"type": str(items["type"])}
    return meta


def _format_parameter_meta(meta: _ParameterMeta) -> str:
    parts: list[str] = []
    parts.append(f"type={json.dumps(meta.type)}")
    if meta.max_length is not None:
        parts.append(f"max_length={meta.max_length}")
    if meta.minimum is not None:
        parts.append(f"minimum={meta.minimum}")
    if meta.maximum is not None:
        parts.append(f"maximum={meta.maximum}")
    if meta.enum is not None:
        enum_vals = ", ".join(json.dumps(v) for v in meta.enum)
        parts.append(f"enum=[{enum_vals}]")
    if meta.items is not None:
        parts.append(f"items={{'type': {json.dumps(meta.items['type'])}}}")
    return f"ParameterMeta({', '.join(parts)})"


def _collect_parameter_meta(api: WebScrapingApiIR) -> dict[str, _ParameterMeta]:
    collected: dict[str, _ParameterMeta] = {}
    for target in api["targets"].values():
        properties: dict[str, Any] = target["parameter_schema"].get("properties", {})
        for name, schema in properties.items():
            if name == "target":
                continue
            if name in collected:
                continue
            collected[name] = _to_parameter_meta(schema)
    return collected


def get_parameters_file(api: WebScrapingApiIR) -> str:
    lines: list[str] = []

    lines.append("# Auto-generated by src/decodo/codegen/web_scraping_api/generate_parameters.py — do not edit")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from typing import Any, TypedDict")
    lines.append("")
    lines.append("")
    lines.append("class ParameterMeta(TypedDict, total=False):")
    lines.append("    type: str")
    lines.append("    max_length: int")
    lines.append("    minimum: float")
    lines.append("    maximum: float")
    lines.append("    enum: list[Any]")
    lines.append("    items: dict[str, Any]")
    lines.append("")
    lines.append("")

    collected = _collect_parameter_meta(api)
    lines.append("parameter_meta: dict[str, ParameterMeta] = {")
    for key, meta in collected.items():
        lines.append(f"    {json.dumps(key)}: {_format_parameter_meta(meta)},")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def generate_parameters_file(dest_dir: str | None = None) -> None:
    ir = fetch_intermediate_representation()
    api = ir["apis"]["webScrapingApi"]
    file_contents = get_parameters_file(api)

    target = dest_dir if dest_dir is not None else out_dir
    os.makedirs(target, exist_ok=True)
    out_path = os.path.join(target, "parameters.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(file_contents)

    count = len(_collect_parameter_meta(api))
    print(f"Generated parameters from {local_ir_path}:")
    print(f"  {out_path} ({count} parameters)")
