from __future__ import annotations

import json
import os
from typing import Any

from .shared import (
    fetch_intermediate_representation,
    local_ir_path,
    out_dir,
    to_enum_member_name,
    to_pascal_case,
)
from .types import WebScrapingApiIR


def _json_schema_type_to_python(schema: dict[str, Any]) -> str:
    if "const" in schema:
        return f"Literal[{json.dumps(schema['const'])}]"
    schema_type = schema.get("type")
    enum_vals = schema.get("enum")
    if isinstance(enum_vals, list) and schema_type == "string":
        literals = ", ".join(json.dumps(v) for v in enum_vals)
        return f"Literal[{literals}]"
    if schema_type == "string":
        return "str"
    if schema_type == "number":
        return "float"
    if schema_type == "integer":
        return "int"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "array":
        return "list[Any]"
    return "Any"


def _is_valid_identifier(name: str) -> bool:
    return name.isidentifier() and not name[0].isdigit()


def _sanitize_field_name(name: str) -> str:
    if _is_valid_identifier(name):
        return name
    return f"f{name}"


def _get_target_parameter_keys(parameter_schema: dict[str, Any]) -> list[str]:
    properties: dict = parameter_schema.get("properties", {})
    return [k for k in properties if k != "target"]


def _get_targets_file_contents(api: WebScrapingApiIR) -> str:
    lines: list[str] = []

    lines.append("# Auto-generated by src/decodo/codegen/web_scraping_api/generate_targets.py — do not edit")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from enum import Enum")
    lines.append("from typing import Annotated, Any, Literal, Union")
    lines.append("")
    lines.append("import pydantic")
    lines.append("")

    target_keys = list(api["targets"].keys())

    lines.append("class Target(str, Enum):")
    if target_keys:
        for key in target_keys:
            member = to_enum_member_name(key)
            lines.append(f"    {member} = {json.dumps(key)}")
    else:
        lines.append("    pass")
    lines.append("")

    lines.append("targets: list[str] = [t.value for t in Target]")
    lines.append("")

    # Override class names for target keys that conflict with reserved names
    CLASS_NAME_OVERRIDES: dict[str, str] = {
        "target": "TargetStoreParams",
    }

    def _class_name(target_key: str) -> str:
        if target_key in CLASS_NAME_OVERRIDES:
            return CLASS_NAME_OVERRIDES[target_key]
        return f"{to_pascal_case(target_key)}Params"

    for target_key, target in api["targets"].items():
        type_name = _class_name(target_key)
        member = to_enum_member_name(target_key)
        properties: dict = target["parameter_schema"].get("properties", {})

        lines.append(f"class {type_name}(pydantic.BaseModel):")
        lines.append(f"    model_config = pydantic.ConfigDict(populate_by_name=True)")
        lines.append(f"    target: Literal[Target.{member}] = Target.{member}")
        params = {k: v for k, v in properties.items() if k != "target"}
        if params:
            for param_key, param_schema in params.items():
                python_type = _json_schema_type_to_python(param_schema)
                field_name = _sanitize_field_name(param_key)
                if field_name != param_key:
                    lines.append(f"    {field_name}: {python_type} | None = pydantic.Field(None, alias={json.dumps(param_key)})")
                else:
                    lines.append(f"    {field_name}: {python_type} | None = None")
        lines.append("")

    lines.append("class TargetMeta(pydantic.BaseModel):")
    lines.append("    group: str")
    lines.append("    response_format: str")
    lines.append("    parameters: list[str]")
    lines.append("")

    lines.append("target_meta: dict[str, TargetMeta] = {")
    for target_key, target in api["targets"].items():
        member = to_enum_member_name(target_key)
        param_keys = _get_target_parameter_keys(target["parameter_schema"])
        params_list = ", ".join(json.dumps(p) for p in param_keys)
        lines.append(f"    Target.{member}.value: TargetMeta(")
        lines.append(f"        group={json.dumps(target['group'])},")
        lines.append(f"        response_format={json.dumps(target['response_format'])},")
        lines.append(f"        parameters=[{params_list}],")
        lines.append("    ),")
    lines.append("}")
    lines.append("")

    # Discriminated union for ScrapeRequest / BatchRequest
    union_parts = " | ".join(_class_name(k) for k in target_keys)
    lines.append(f"ScrapeRequest = Annotated[")
    lines.append(f"    Union[{union_parts}],")
    lines.append(f"    pydantic.Field(discriminator='target'),")
    lines.append(f"]")
    lines.append(f"BatchRequest = ScrapeRequest")
    lines.append("")

    return "\n".join(lines)


def generate_targets_file() -> None:
    ir = fetch_intermediate_representation()
    api = ir["apis"]["webScrapingApi"]
    file_contents = _get_targets_file_contents(api)

    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "targets.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(file_contents)

    target_count = len(api["targets"])
    print(f"Generated targets from {local_ir_path}:")
    print(f"  {out_path} ({target_count} targets)")
