from __future__ import annotations

import json
import os
from typing import Any

from .shared import (
    fetch_intermediate_representation,
    local_ir_path,
    out_dir,
    targets_enum_path,
    to_enum_member_name,
    to_pascal_case,
)
from .types import WebScrapingApiIR


def _json_schema_type_to_python(schema: dict[str, Any]) -> str:
    if "const" in schema:
        return f"Literal[{json.dumps(schema['const'])}]"
    schema_type = schema.get("type")
    enum_vals = schema.get("enum")
    if isinstance(enum_vals, list) and schema_type == "string":
        literals = ", ".join(json.dumps(v) for v in enum_vals)
        return f"Literal[{literals}]"
    if schema_type == "string":
        return "str"
    if schema_type == "number":
        return "float"
    if schema_type == "integer":
        return "int"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "array":
        return "list[Any]"
    return "Any"


def _is_valid_identifier(name: str) -> bool:
    return name.isidentifier() and not name[0].isdigit()


def _sanitize_field_name(name: str) -> str:
    if _is_valid_identifier(name):
        return name
    return f"f{name}"


def _get_target_parameter_keys(parameter_schema: dict[str, Any]) -> list[str]:
    properties: dict[str, Any] = parameter_schema.get("properties", {})
    return [k for k in properties if k != "target"]


def _get_targets_enum_file_contents(api: WebScrapingApiIR) -> str:
    lines: list[str] = []

    lines.append("# Minimal target enum — committed to source.")
    lines.append("# Run `python -m decodo.codegen.codegen` to regenerate when the IR schema changes.")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from enum import StrEnum")
    lines.append("")
    lines.append("")

    target_keys = list(api["targets"].keys())

    lines.append("class Target(StrEnum):")
    if target_keys:
        for key in target_keys:
            member = to_enum_member_name(key)
            lines.append(f"    {member} = {json.dumps(key)}")
    else:
        lines.append("    pass")
    lines.append("")
    lines.append("")

    lines.append("targets: list[str] = [t.value for t in Target]")
    lines.append("")

    return "\n".join(lines)


def _get_targets_file_contents(api: WebScrapingApiIR) -> str:
    lines: list[str] = []

    lines.append("# Auto-generated by src/decodo/codegen/web_scraping_api/generate_targets.py — do not edit")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from typing import Annotated, Any, Literal, Union")
    lines.append("")
    lines.append("import pydantic")
    lines.append("")
    lines.append("from decodo.targets import Target")
    lines.append("")

    target_keys = list(api["targets"].keys())

    # Override class names for target keys that conflict with reserved names
    CLASS_NAME_OVERRIDES: dict[str, str] = {
        "target": "TargetStoreParams",
    }

    BATCH_CLASS_NAME_OVERRIDES: dict[str, str] = {
        "target": "TargetStoreBatchParams",
    }

    def _class_name(target_key: str) -> str:
        if target_key in CLASS_NAME_OVERRIDES:
            return CLASS_NAME_OVERRIDES[target_key]
        return f"{to_pascal_case(target_key)}Params"

    def _batch_class_name(target_key: str) -> str:
        if target_key in BATCH_CLASS_NAME_OVERRIDES:
            return BATCH_CLASS_NAME_OVERRIDES[target_key]
        return f"{to_pascal_case(target_key)}BatchParams"

    # Emit per-target sync Params classes
    for target_key, target in api["targets"].items():
        type_name = _class_name(target_key)
        member = to_enum_member_name(target_key)
        properties: dict[str, Any] = target["parameter_schema"].get("properties", {})

        lines.append(f"class {type_name}(pydantic.BaseModel):")
        lines.append("    model_config = pydantic.ConfigDict(populate_by_name=True, extra='forbid')")
        lines.append(f"    target: Literal[Target.{member}] = Target.{member}")
        params = {k: v for k, v in properties.items() if k != "target"}
        if params:
            for param_key, param_schema in params.items():
                python_type = _json_schema_type_to_python(param_schema)
                field_name = _sanitize_field_name(param_key)
                if field_name != param_key:
                    lines.append(
                        f"    {field_name}: {python_type} | None = pydantic.Field(None, alias={json.dumps(param_key)})"
                    )  # noqa: E501
                else:
                    lines.append(f"    {field_name}: {python_type} | None = None")
        lines.append("")

    # Emit per-target batch Params classes (url/query become list[str])
    for target_key, target in api["targets"].items():
        batch_type_name = _batch_class_name(target_key)
        member = to_enum_member_name(target_key)
        properties = target["parameter_schema"].get("properties", {})

        lines.append(f"class {batch_type_name}(pydantic.BaseModel):")
        lines.append("    model_config = pydantic.ConfigDict(populate_by_name=True, extra='forbid')")
        lines.append(f"    target: Literal[Target.{member}] = Target.{member}")
        params = {k: v for k, v in properties.items() if k != "target"}
        if params:
            for param_key, param_schema in params.items():
                field_name = _sanitize_field_name(param_key)
                if param_key in ("url", "query"):
                    python_type = "list[str]"
                else:
                    python_type = _json_schema_type_to_python(param_schema)
                if field_name != param_key:
                    lines.append(
                        f"    {field_name}: {python_type} | None = pydantic.Field(None, alias={json.dumps(param_key)})"
                    )  # noqa: E501
                else:
                    lines.append(f"    {field_name}: {python_type} | None = None")
        lines.append("")

    # target_meta as plain dict-of-dicts (no TargetMeta class here)
    lines.append("target_meta: dict[str, dict[str, Any]] = {")
    for target_key, target in api["targets"].items():
        member = to_enum_member_name(target_key)
        param_keys = _get_target_parameter_keys(target["parameter_schema"])
        params_list = ", ".join(json.dumps(p) for p in param_keys)
        lines.append(f"    Target.{member}.value: {{")
        lines.append(f'        "group": {json.dumps(target["group"])},')
        lines.append(f'        "response_format": {json.dumps(target["response_format"])},')
        lines.append(f'        "parameters": [{params_list}],')
        lines.append("    },")
    lines.append("}")
    lines.append("")

    # Discriminated union for ScrapeRequest
    union_parts = " | ".join(_class_name(k) for k in target_keys)
    lines.append("ScrapeRequest = Annotated[")
    lines.append(f"    Union[{union_parts}],")
    lines.append("    pydantic.Field(discriminator='target'),")
    lines.append("]")
    lines.append("")

    # Discriminated union for BatchRequest
    batch_union_parts = " | ".join(_batch_class_name(k) for k in target_keys)
    lines.append("BatchRequest = Annotated[")
    lines.append(f"    Union[{batch_union_parts}],")
    lines.append("    pydantic.Field(discriminator='target'),")
    lines.append("]")
    lines.append("")

    return "\n".join(lines)


def generate_targets_enum_file() -> None:
    ir = fetch_intermediate_representation()
    api = ir["apis"]["webScrapingApi"]
    file_contents = _get_targets_enum_file_contents(api)

    with open(targets_enum_path, "w", encoding="utf-8") as f:
        f.write(file_contents)

    target_count = len(api["targets"])
    print(f"Generated Target enum from {local_ir_path}:")
    print(f"  {targets_enum_path} ({target_count} targets)")


def generate_targets_file(dest_dir: str | None = None) -> None:
    ir = fetch_intermediate_representation()
    api = ir["apis"]["webScrapingApi"]
    file_contents = _get_targets_file_contents(api)

    target = dest_dir if dest_dir is not None else out_dir
    os.makedirs(target, exist_ok=True)
    out_path = os.path.join(target, "targets.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(file_contents)

    target_count = len(api["targets"])
    print(f"Generated target Params from {local_ir_path}:")
    print(f"  {out_path} ({target_count} targets)")
