from .api.web_scraping_api import WebScrapingApi
from .client import DecodoClient, DecodoConfig, WebScrapingApiConfig
from .errors import (
    AuthenticationError,
    DecodoError,
    RateLimitError,
    TimeoutError,
    ValidationError,
)
from .schema.bundled_schema import BundledSchema
from .schema.remote_schema import RemoteSchema
from .schema.types import DecodoSchema, RemoteSchemaLoadOptions
from .targets import Target, targets
from .types.responses import (
    AsyncTaskResponse,
    BatchResponse,
    ResultEntry,
    SyncResponse,
    TaskMetadata,
    TaskResultsResponse,
    TaskStatus,
)

_codegen_available = False
try:
    from .generated.parameters import ParameterMeta, parameter_meta  # noqa: F401
    from .generated.targets import (  # noqa: F401
        AirbnbBatchParams,
        AirbnbParams,
        AmazonBatchParams,
        AmazonBestsellersBatchParams,
        AmazonBestsellersParams,
        AmazonParams,
        AmazonPricingBatchParams,
        AmazonPricingParams,
        AmazonProductBatchParams,
        AmazonProductParams,
        AmazonSearchBatchParams,
        AmazonSearchParams,
        AmazonSellersBatchParams,
        AmazonSellersParams,
        AppleAppStoreBatchParams,
        AppleAppStoreParams,
        AutotraderBatchParams,
        AutotraderParams,
        BatchRequest,
        BbbBatchParams,
        BbbParams,
        BingBatchParams,
        BingParams,
        BingSearchBatchParams,
        BingSearchParams,
        ChatgptBatchParams,
        ChatgptParams,
        EcommerceBatchParams,
        EcommerceParams,
        GeminiBatchParams,
        GeminiParams,
        GoogleAdsBatchParams,
        GoogleAdsParams,
        GoogleAiModeBatchParams,
        GoogleAiModeParams,
        GoogleBatchParams,
        GoogleLensBatchParams,
        GoogleLensParams,
        GoogleMapsBatchParams,
        GoogleMapsParams,
        GoogleParams,
        GoogleSearchBatchParams,
        GoogleSearchParams,
        GoogleShoppingProductBatchParams,
        GoogleShoppingProductParams,
        GoogleShoppingSearchBatchParams,
        GoogleShoppingSearchParams,
        GoogleSuggestBatchParams,
        GoogleSuggestParams,
        GoogleTravelHotelsBatchParams,
        GoogleTravelHotelsParams,
        GoogleTrendsExploreBatchParams,
        GoogleTrendsExploreParams,
        InstagramGraphqlProfileBatchParams,
        InstagramGraphqlProfileParams,
        LowesSearchBatchParams,
        LowesSearchParams,
        MobileBatchParams,
        MobileParams,
        PerplexityBatchParams,
        PerplexityParams,
        RedditPostBatchParams,
        RedditPostParams,
        RedditSubredditBatchParams,
        RedditSubredditParams,
        RedditUserBatchParams,
        RedditUserParams,
        ScrapeRequest,
        TargetProductBatchParams,
        TargetProductParams,
        TargetSearchBatchParams,
        TargetSearchParams,
        TargetStoreBatchParams,
        TargetStoreParams,
        TiktokBatchParams,
        TiktokParams,
        TiktokPostBatchParams,
        TiktokPostParams,
        TiktokShopProductBatchParams,
        TiktokShopProductParams,
        TiktokShopSearchBatchParams,
        TiktokShopSearchParams,
        UniversalBatchParams,
        UniversalEcommerceBatchParams,
        UniversalEcommerceParams,
        UniversalParams,
        WalmartBatchParams,
        WalmartParams,
        WalmartProductBatchParams,
        WalmartProductParams,
        WalmartSearchBatchParams,
        WalmartSearchParams,
        YoutubeChannelBatchParams,
        YoutubeChannelParams,
        YoutubeMetadataBatchParams,
        YoutubeMetadataParams,
        YoutubeSearchBatchParams,
        YoutubeSearchMaxBatchParams,
        YoutubeSearchMaxParams,
        YoutubeSearchParams,
        YoutubeSubtitlesBatchParams,
        YoutubeSubtitlesParams,
        YoutubeTranscriptBatchParams,
        YoutubeTranscriptParams,
        YoutubeVideoBatchParams,
        YoutubeVideoParams,
        target_meta,
    )
    _codegen_available = True
except ImportError:
    pass

_CODEGEN_NAMES: frozenset[str] = frozenset(
    [
        "AirbnbBatchParams",
        "AirbnbParams",
        "AmazonBatchParams",
        "AmazonBestsellersBatchParams",
        "AmazonBestsellersParams",
        "AmazonParams",
        "AmazonPricingBatchParams",
        "AmazonPricingParams",
        "AmazonProductBatchParams",
        "AmazonProductParams",
        "AmazonSearchBatchParams",
        "AmazonSearchParams",
        "AmazonSellersBatchParams",
        "AmazonSellersParams",
        "AppleAppStoreBatchParams",
        "AppleAppStoreParams",
        "AutotraderBatchParams",
        "AutotraderParams",
        "BatchRequest",
        "BbbBatchParams",
        "BbbParams",
        "BingBatchParams",
        "BingParams",
        "BingSearchBatchParams",
        "BingSearchParams",
        "ChatgptBatchParams",
        "ChatgptParams",
        "EcommerceBatchParams",
        "EcommerceParams",
        "GeminiBatchParams",
        "GeminiParams",
        "GoogleAdsBatchParams",
        "GoogleAdsParams",
        "GoogleAiModeBatchParams",
        "GoogleAiModeParams",
        "GoogleBatchParams",
        "GoogleLensBatchParams",
        "GoogleLensParams",
        "GoogleMapsBatchParams",
        "GoogleMapsParams",
        "GoogleParams",
        "GoogleSearchBatchParams",
        "GoogleSearchParams",
        "GoogleShoppingProductBatchParams",
        "GoogleShoppingProductParams",
        "GoogleShoppingSearchBatchParams",
        "GoogleShoppingSearchParams",
        "GoogleSuggestBatchParams",
        "GoogleSuggestParams",
        "GoogleTravelHotelsBatchParams",
        "GoogleTravelHotelsParams",
        "GoogleTrendsExploreBatchParams",
        "GoogleTrendsExploreParams",
        "InstagramGraphqlProfileBatchParams",
        "InstagramGraphqlProfileParams",
        "LowesSearchBatchParams",
        "LowesSearchParams",
        "MobileBatchParams",
        "MobileParams",
        "ParameterMeta",
        "PerplexityBatchParams",
        "PerplexityParams",
        "RedditPostBatchParams",
        "RedditPostParams",
        "RedditSubredditBatchParams",
        "RedditSubredditParams",
        "RedditUserBatchParams",
        "RedditUserParams",
        "ScrapeRequest",
        "TargetProductBatchParams",
        "TargetProductParams",
        "TargetSearchBatchParams",
        "TargetSearchParams",
        "TargetStoreBatchParams",
        "TargetStoreParams",
        "TiktokBatchParams",
        "TiktokParams",
        "TiktokPostBatchParams",
        "TiktokPostParams",
        "TiktokShopProductBatchParams",
        "TiktokShopProductParams",
        "TiktokShopSearchBatchParams",
        "TiktokShopSearchParams",
        "UniversalBatchParams",
        "UniversalEcommerceBatchParams",
        "UniversalEcommerceParams",
        "UniversalParams",
        "WalmartBatchParams",
        "WalmartParams",
        "WalmartProductBatchParams",
        "WalmartProductParams",
        "WalmartSearchBatchParams",
        "WalmartSearchParams",
        "YoutubeChannelBatchParams",
        "YoutubeChannelParams",
        "YoutubeMetadataBatchParams",
        "YoutubeMetadataParams",
        "YoutubeSearchBatchParams",
        "YoutubeSearchMaxBatchParams",
        "YoutubeSearchMaxParams",
        "YoutubeSearchParams",
        "YoutubeSubtitlesBatchParams",
        "YoutubeSubtitlesParams",
        "YoutubeTranscriptBatchParams",
        "YoutubeTranscriptParams",
        "YoutubeVideoBatchParams",
        "YoutubeVideoParams",
        "parameter_meta",
        "target_meta",
    ]
)


def __getattr__(name: str) -> object:
    if name in _CODEGEN_NAMES:
        raise ImportError(
            f"'{name}' requires generated types. "
            "Editable install: run python -m decodo.codegen.codegen, then use 'from decodo import ...'. "
            "Pip install: run python -m decodo.codegen.codegen --out-dir ./decodo_generated, "
            "then use 'from decodo_generated.targets import ...'."
        )
    raise AttributeError(f"module 'decodo' has no attribute {name!r}")


__all__ = [
    "DecodoClient",
    "DecodoConfig",
    "WebScrapingApiConfig",
    "WebScrapingApi",
    "BundledSchema",
    "RemoteSchema",
    "DecodoSchema",
    "RemoteSchemaLoadOptions",
    "Target",
    "targets",
    "SyncResponse",
    "AsyncTaskResponse",
    "BatchResponse",
    "TaskMetadata",
    "TaskResultsResponse",
    "TaskStatus",
    "ResultEntry",
    "DecodoError",
    "AuthenticationError",
    "RateLimitError",
    "ValidationError",
    "TimeoutError",
]

if _codegen_available:
    __all__ += list(_CODEGEN_NAMES)
